// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDcsy90zMlNhilSCAAQMlFtxPEo416A4jI',
    appId: '1:1029978666965:web:8a63f86e088ddfecf22f5c',
    messagingSenderId: '1029978666965',
    projectId: 'flutterfirebase-74e74',
    authDomain: 'flutterfirebase-74e74.firebaseapp.com',
    storageBucket: 'flutterfirebase-74e74.appspot.com',
    measurementId: 'G-EYX78FRESL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBaT5TzGnsY7Zyg6D019hymRJMt-j6TL4c',
    appId: '1:1029978666965:android:e15bc791220d946df22f5c',
    messagingSenderId: '1029978666965',
    projectId: 'flutterfirebase-74e74',
    storageBucket: 'flutterfirebase-74e74.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDbX-Zgc_vLkBvraMZ_s6UZoqizTbxoJGc',
    appId: '1:1029978666965:ios:53eca6b7d05d5f21f22f5c',
    messagingSenderId: '1029978666965',
    projectId: 'flutterfirebase-74e74',
    storageBucket: 'flutterfirebase-74e74.appspot.com',
    iosBundleId: 'com.example.firebaseApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDbX-Zgc_vLkBvraMZ_s6UZoqizTbxoJGc',
    appId: '1:1029978666965:ios:9e13415fa5995945f22f5c',
    messagingSenderId: '1029978666965',
    projectId: 'flutterfirebase-74e74',
    storageBucket: 'flutterfirebase-74e74.appspot.com',
    iosBundleId: 'com.example.firebaseApp.RunnerTests',
  );
}
